[build-system]
requires = ["setuptools==68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "thesis-sastllm"
version = "0.1.0"
description = "..."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv==0.9.9",
    "kneed==0.8.6",
    "lightning==2.6.1",
    "matplotlib==3.10.8",
    "numpy==2.4.4",
    "pip==26.0.1",
    "psycopg[binary,pool]==3.3.3",
    "qdrant-client==1.17.1",
    "sqlalchemy==2.0.49",
    "tensorboard==2.20.0",
    "tiktoken==0.12.0",
    "tree-sitter==0.25.2",
    "typer==0.24.2",
    "torch==2.11.0",
    "torchvision==0.26.0",
    "torchaudio==2.11.0",
    "sentence-transformers==5.4.1",
    "datasets==4.8.4",
    "huggingface-hub==1.11.0",
    "shap==0.51.0",
    "spacy==3.8.11",
    "langchain==1.2.15",
    "pydantic-settings==2.14.0",
    "pydantic==2.12.5",
    "langchain-google-genai==4.2.2",
    "langchain-openai==1.2.0",
    "chardet==7.4.3",
]

[project.optional-dependencies]
dev = ["ruff==0.15.11", "black==26.3.1", "mypy==1.20.2"]

[tool.ruff]
line-length = 150
target-version = "py312"
exclude = [
    "build",
    "dist",
    "qdrant_storage",
    "models/trained_models",
    "**/migrations/**",
]
extend-select = ["E", "F", "I"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
line-ending = "lf"

[project.scripts]
sastllm = "scripts.cli:main"

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]
torchaudio = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true


[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["sastllm*", "scripts*"]
exclude = ["tests*", "evaluations*", "examples*"]

[tool.pyright]
venvPath = "."
venv = ".venv"
